version: 0.2

env:
  variables:
    NEXT_PUBLIC_INITIALIZE_PAGE_ENABLED: true
    NEXT_PUBLIC_DEVNET_PROGRAM_ID: R2y9ip6mxmWUj4pt54jP2hz2dgvMozy9VTSwMWE7evs
    NEXT_PUBLIC_MAINNET_PROGRAM_ID: R2y9ip6mxmWUj4pt54jP2hz2dgvMozy9VTSwMWE7evs
    NEXT_PUBLIC_DEVNET_DEX_PROGRAM_ID: DESVgJVGajEgKGXhb6XmqDHGz3VjdgP7rEVESBgxmroY
    NEXT_PUBLIC_MAINNET_DEX_PROGRAM_ID: 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin
    NEXT_PUBLIC_DEVNET_FAUCET_USDC: E6wQSMPGqHn7dqEMeWcSVfjdkwd8ED5CncQ9BtMNGtUG
    NEXT_PUBLIC_DEVNET_FAUCET_BTC: 97z3NzcDxqRMyE7F73PuHEmAbA72S7eDopjhe7GTymTk
    NEXT_PUBLIC_DEVNET_FAUCET_PSY: 7jJJnHWagPPG544FtxSVp8eD52FwCsARcqqup1q3XVio
  secrets-manager:
    SENTRY_AUTH_TOKEN: '${SecretsArn}:SENTRY_AUTH_TOKEN'

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --cache-from $ECR_REPOSITORY_URI:latest -t $ECR_REPOSITORY_URI:latest --build-arg SHORT_SHA=${COMMIT_HASH} --build-arg SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN} .
      - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - printf '{"ImageURI":"%s:%s"}' $ECR_REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
